#!/usr/bin/env python3
"""Build the committed test fixtures from acquired filings.

FIXTURE STRATEGY (decided in docs/sprints/SPRINT-0003.md):

    Small deterministic extracted fixtures live in Git. Raw sources stay in object storage,
    which is gitignored. A manifest pins every source URL and SHA-256 so the extracted fixtures
    are provably faithful to a specific filed document.

Apple's FY2025 10-K alone is 3.4 MB of source objects. Committing four filings' worth would put
tens of megabytes of binary-like content into every clone, forever, for documents SEC already
hosts. Instead we commit the renderer report inventory, which is what canonical footnote grouping
actually reads, plus a manifest that lets anyone re-fetch and verify the originals.

Run after acquisition:

    python scripts/build_fixtures.py
    python scripts/build_fixtures.py --verify   # re-check hashes against SEC, needs network
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from packages.storage import FilesystemObjectStore, sha256_bytes  # noqa: E402

FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures" / "filings"
OBJECT_ROOT = REPO_ROOT / "var" / "objects"

_REPORT = re.compile(r"<Report[^>]*>(.*?)</Report>", re.S)


def _tag(block: str, name: str) -> str:
    match = re.search(rf"<{name}>(.*?)</{name}>", block, re.S)
    return (match.group(1).strip() if match else "").replace("&amp;", "&")


def extract_report_inventory(filing_summary_xml: str) -> list[dict[str, object]]:
    """The renderer's report list, normalized.

    This is the input to canonicalization stage 1. Keeping it as a small YAML file rather than
    re-parsing 42 KB of XML in every test keeps the fixture readable in review, which raw XML is
    not.
    """
    inventory = []
    for index, block in enumerate(_REPORT.findall(filing_summary_xml), start=1):
        inventory.append(
            {
                "position": index,
                "menu_category": _tag(block, "MenuCategory"),
                "short_name": _tag(block, "ShortName"),
                "long_name": _tag(block, "LongName"),
                "role": _tag(block, "Role"),
                "file_name": _tag(block, "HtmlFileName") or _tag(block, "XmlFileName"),
            }
        )
    return inventory


def _yaml_quote(value: object) -> str:
    """Quote a scalar for YAML. Every identifier is quoted, never bare.

    YAML 1.2 parses an unquoted 0000320193 as the integer 320193, which destroys the leading
    zeros that make it a valid CIK. Quoting unconditionally is cheaper than deciding per field.
    """
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_inventory_yaml(path: Path, accession: str, inventory: list[dict[str, object]]) -> None:
    lines = [
        "# Renderer report inventory, extracted from FilingSummary.xml.",
        "# Generated by scripts/build_fixtures.py. Do not edit by hand.",
        f"accession: {_yaml_quote(accession)}",
        f"report_count: {len(inventory)}",
        "reports:",
    ]
    for row in inventory:
        lines.append(f"  - position: {row['position']}")
        lines.append(f"    menu_category: {_yaml_quote(row['menu_category'])}")
        lines.append(f"    short_name: {_yaml_quote(row['short_name'])}")
        lines.append(f"    long_name: {_yaml_quote(row['long_name'])}")
        lines.append(f"    role: {_yaml_quote(row['role'])}")
        lines.append(f"    file_name: {_yaml_quote(row['file_name'])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build(acquisitions: list[dict]) -> dict[str, object]:
    store = FilesystemObjectStore(OBJECT_ROOT)
    FIXTURE_ROOT.mkdir(parents=True, exist_ok=True)

    manifest_lines = [
        "# Source manifest for the committed filing fixtures.",
        "#",
        "# Every entry pins the accession, the SEC URL, and the SHA-256 of the object as",
        "# retrieved. The extracted fixtures beside this file are derived from exactly these",
        "# bytes. Re-fetch and compare with: python scripts/build_fixtures.py --verify",
        "#",
        "# The raw objects themselves are NOT committed: they are 8.4 MiB for four filings and",
        "# SEC hosts them authoritatively. They live in var/objects/, which is gitignored.",
        "filings:",
    ]
    written = 0

    for record in acquisitions:
        accession = record["accession"]
        folder = FIXTURE_ROOT / accession
        folder.mkdir(parents=True, exist_ok=True)

        manifest_lines += [
            f"  - accession: {_yaml_quote(accession)}",
            f"    cik: {_yaml_quote(record['cik'])}",
            f"    form: {_yaml_quote(record['form'])}",
            f"    era: {_yaml_quote(record['era'])}",
            "    objects:",
        ]
        for obj in record["objects"]:
            manifest_lines += [
                f"      - role: {_yaml_quote(obj['role'])}",
                f"        url: {_yaml_quote(obj['url'])}",
                f"        sha256: {_yaml_quote(obj['sha256'])}",
                f"        size_bytes: {obj['size_bytes']}",
            ]

        summary_key = next(
            o["storage_key"] for o in record["objects"] if o["role"] == "filing_summary"
        )
        summary_xml = store.get_text(summary_key)

        (folder / "filing-summary.xml").write_text(summary_xml, encoding="utf-8")
        inventory = extract_report_inventory(summary_xml)
        write_inventory_yaml(folder / "report-inventory.yaml", accession, inventory)
        written += 2

        manifest_lines.append(
            f"    filing_summary_sha256: {_yaml_quote(sha256_bytes(summary_xml.encode()))}"
        )
        manifest_lines.append(f"    report_count: {len(inventory)}")

    (FIXTURE_ROOT / "manifest.yaml").write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
    written += 1
    return {"files_written": written, "filings": len(acquisitions)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--acquisitions",
        default=str(REPO_ROOT / "var" / "acquisition.json"),
        help="acquisition provenance produced by the retrieval run",
    )
    args = parser.parse_args()

    import json

    acquisitions = json.loads(Path(args.acquisitions).read_text())
    result = build(acquisitions)

    total = sum(p.stat().st_size for p in FIXTURE_ROOT.rglob("*") if p.is_file())
    print(f"wrote {result['files_written']} fixture files for {result['filings']} filings")
    print(f"fixture tree: {total:,} bytes ({total / 1024:.1f} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
