"""Real-fixture ownership regression for all four Apple filings, and proof it can fail.

The fixtures are DERIVED from the preserved bytes, not invented: table offsets, tagged-span
geometry, and the concept-to-role index are extracted from the real primary documents and
presentation linkbases, and the expected classification is what the implementation measured
against them. That keeps the regression real while letting the suite run offline on a fresh clone
without the 6 MB of source documents.

`tests/fixtures/filings/<accession>/table-ownership.json`, regenerated by
`scripts/build_ownership_fixtures.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from packages.footnote_canonicalizer import (
    CANONICAL_FOOTNOTE,
    COMPLETE,
    EXCLUDED_FILING_SECTION,
    FINANCIAL_STATEMENT,
    OTHER_FILING_REPORT,
    PARTIAL,
    UNRESOLVED,
    ExclusionList,
    canonicalize,
    classify_tables,
    evaluate,
)
from packages.footnote_extractor import NoteHeading, read_inventory
from packages.footnote_extractor.presentation import PresentationLinkbase, RolePresentation
from packages.footnote_extractor.tagged_blocks import TaggedSpan

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "filings"

TEN_K = "0000320193-25-000079"
TEN_QS = ("0000320193-25-000008", "0000320193-25-000057", "0000320193-25-000073")
ALL_FILINGS = (TEN_K, *TEN_QS)

# Measured against the preserved filings. See docs/sprints/SPRINT-0004.md.
EXPECTED_CENSUS = {
    TEN_K: {"total": 62, CANONICAL_FOOTNOTE: 26, FINANCIAL_STATEMENT: 5, UNRESOLVED: 0},
    "0000320193-25-000008": {
        "total": 37,
        CANONICAL_FOOTNOTE: 11,
        FINANCIAL_STATEMENT: 5,
        UNRESOLVED: 0,
    },
    "0000320193-25-000057": {
        "total": 37,
        CANONICAL_FOOTNOTE: 11,
        FINANCIAL_STATEMENT: 5,
        UNRESOLVED: 0,
    },
    "0000320193-25-000073": {
        "total": 38,
        CANONICAL_FOOTNOTE: 12,
        FINANCIAL_STATEMENT: 5,
        UNRESOLVED: 0,
    },
}


class FixtureTable:
    def __init__(self, entry: dict) -> None:
        self.external_id = entry["external_id"]
        self.source_offset = entry["source_offset"]
        self.raw_html = "x" * entry["raw_length"]


def load(accession: str) -> dict:
    path = FIXTURES / accession / "table-ownership.json"
    if not path.exists():  # pragma: no cover - fixture is committed
        pytest.fail(f"ownership fixture missing: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def build(accession: str, fixture: dict | None = None):
    fixture = fixture or load(accession)
    inventory = read_inventory(FIXTURES / accession / "filing-summary.xml")
    note_count = len(
        [
            r
            for r in inventory.candidates()
            if "/ecd/" not in (r.role or "") and "/cyd/" not in (r.role or "")
        ]
    )
    result = canonicalize(
        accession=accession,
        inventory=inventory,
        headings=tuple(NoteHeading(i, f"Note {i}", i, True) for i in range(1, note_count + 1)),
        exclusions=ExclusionList.load(),
    )
    linkbase = PresentationLinkbase(
        roles={
            role: RolePresentation(
                role,
                tuple(c for c, roles in fixture["concept_roles"].items() if role in roles),
            )
            for role in {r for roles in fixture["concept_roles"].values() for r in roles}
        }
    )
    spans = [
        TaggedSpan(
            concept=s["concept"],
            start=s["start"],
            end=s["end"],
            tag="ix:nonnumeric",
            is_continuation=s["is_continuation"],
        )
        for s in fixture["text_block_spans"]
    ]
    numeric = [
        TaggedSpan(concept=s["concept"], start=s["start"], end=s["start"] + 1, tag="ix:nonfraction")
        for s in fixture["numeric_spans"]
    ]
    ownership = classify_tables(
        result,
        [FixtureTable(t) for t in fixture["tables"]],
        spans,
        linkbase,
        statement_roles=set(fixture["statement_roles"]),
        numeric_spans=numeric,
    )
    return result, ownership, fixture


# --- the regression ---------------------------------------------------------------------------


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_ownership_matches_the_measured_census(accession: str) -> None:
    _, ownership, _ = build(accession)
    expected = EXPECTED_CENSUS[accession]
    assert ownership.total == expected["total"]
    assert ownership.count(CANONICAL_FOOTNOTE) == expected[CANONICAL_FOOTNOTE]
    assert ownership.count(FINANCIAL_STATEMENT) == expected[FINANCIAL_STATEMENT]
    assert ownership.count(UNRESOLVED) == expected[UNRESOLVED]


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_no_canonical_footnote_table_is_unresolved(accession: str) -> None:
    """THE ACCEPTANCE CRITERION. Zero unresolved, on every filing."""
    _, ownership, _ = build(accession)
    assert ownership.unresolved == []
    assert not ownership.has_unresolved_footnote_tables


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_every_table_receives_exactly_one_classification(accession: str) -> None:
    _, ownership, _ = build(accession)
    counts = sum(
        ownership.count(k)
        for k in (
            CANONICAL_FOOTNOTE,
            EXCLUDED_FILING_SECTION,
            FINANCIAL_STATEMENT,
            OTHER_FILING_REPORT,
            UNRESOLVED,
        )
    )
    assert counts == ownership.total


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_ownership_reproduces_the_committed_expectation(accession: str) -> None:
    """Every table's classification and owner, not only the totals.

    A census can match while individual tables are attributed to the wrong notes.
    """
    _, ownership, fixture = build(accession)
    actual = {
        o.external_id: {"classification": o.classification, "owner_role_uri": o.owner_role_uri}
        for o in ownership.ownership
    }
    assert actual == fixture["expected_ownership"]


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_a_footnote_owned_table_always_names_its_owner(accession: str) -> None:
    """The database check constraint added in migration 0002 requires exactly this."""
    _, ownership, _ = build(accession)
    for item in ownership.ownership:
        if item.classification == CANONICAL_FOOTNOTE:
            assert item.owner_role_uri
        else:
            assert item.owner_role_uri is None


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_no_excluded_disclosure_table_is_attributed_to_a_footnote(accession: str) -> None:
    result, ownership, _ = build(accession)
    excluded_roles = {n.role_uri for n in result.excluded}
    for item in ownership.ownership:
        assert item.owner_role_uri not in excluded_roles


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_no_statement_table_is_attributed_to_a_footnote(accession: str) -> None:
    _, ownership, fixture = build(accession)
    statements = set(fixture["statement_roles"])
    for item in ownership.ownership:
        if item.classification == FINANCIAL_STATEMENT:
            assert item.owner_role_uri is None
        assert item.owner_role_uri not in statements


def test_every_owner_is_one_of_the_thirteen_notes() -> None:
    result, ownership, _ = build(TEN_K)
    note_roles = {n.role_uri for n in result.footnotes}
    owners = {o.owner_role_uri for o in ownership.ownership if o.is_footnote_owned}
    assert owners <= note_roles
    assert len(note_roles) == 13


def test_ownership_is_reproducible_across_runs() -> None:
    first = build(TEN_K)[1]
    second = build(TEN_K)[1]
    assert first.as_record() == second.as_record()
    assert [o.as_evidence() for o in first.ownership] == [o.as_evidence() for o in second.ownership]


def test_the_continuation_chain_is_what_makes_the_extra_tables_ownable() -> None:
    """Three 10-K tables live in continuation regions rather than inside the declaring element.

    Dropping continuation spans loses them, which is the false negative this fixture guards.
    """
    _, ownership, fixture = build(TEN_K)
    without = [s for s in fixture["text_block_spans"] if not s["is_continuation"]]
    assert len(without) < len(fixture["text_block_spans"])

    reduced = dict(fixture)
    reduced["text_block_spans"] = without
    _, degraded, _ = build(TEN_K, reduced)
    assert degraded.count(CANONICAL_FOOTNOTE) < ownership.count(CANONICAL_FOOTNOTE)


# --- mutation proofs ---------------------------------------------------------------------------


def test_mutation_assigning_a_table_to_the_wrong_note_fails_reconciliation() -> None:
    """The required proof: a wrong owner must break the regression, not pass it."""
    _, ownership, fixture = build(TEN_K)
    actual = {
        o.external_id: {"classification": o.classification, "owner_role_uri": o.owner_role_uri}
        for o in ownership.ownership
    }
    owned = [k for k, v in actual.items() if v["classification"] == CANONICAL_FOOTNOTE]
    first, second = owned[0], owned[1]

    tampered = dict(actual)
    tampered[first] = {
        "classification": CANONICAL_FOOTNOTE,
        "owner_role_uri": actual[second]["owner_role_uri"],
    }
    assert tampered != fixture["expected_ownership"]


def test_mutation_an_unresolved_footnote_table_prevents_complete() -> None:
    result, ownership, _ = build(TEN_K)
    assert evaluate(result, ownership).extraction_status == COMPLETE

    from packages.footnote_canonicalizer.ownership import TableOwnership

    ownership.ownership.append(
        TableOwnership(
            external_id="T999",
            classification=UNRESOLVED,
            concept="us-gaap:SomethingTextBlock",
            reason="deliberate mutation",
        )
    )
    assert ownership.has_unresolved_footnote_tables
    assert evaluate(result, ownership).extraction_status == PARTIAL


def test_mutation_reclassifying_an_excluded_table_as_a_footnote_is_detected() -> None:
    _, ownership, fixture = build(TEN_K)
    actual = {
        o.external_id: {"classification": o.classification, "owner_role_uri": o.owner_role_uri}
        for o in ownership.ownership
    }
    other = next(k for k, v in actual.items() if v["classification"] == OTHER_FILING_REPORT)
    tampered = dict(actual)
    tampered[other] = {"classification": CANONICAL_FOOTNOTE, "owner_role_uri": "http://x/role/Debt"}
    assert tampered != fixture["expected_ownership"]


# --- fixture provenance --------------------------------------------------------------------------


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_the_fixture_names_the_bytes_it_came_from(accession: str) -> None:
    """A derived fixture is only as trustworthy as its ability to identify its source.

    Without hashes, a fixture regenerated from different bytes is indistinguishable from one
    regenerated from the same bytes, and the regression silently starts testing something else.
    """
    provenance = load(accession)["provenance"]
    assert provenance["generated_by"] == "python scripts/build_ownership_fixtures.py"
    assert provenance["parser_versions"]["canonicalizer"]
    assert provenance["parser_versions"]["table_parser"]

    roles = {s["role"] for s in provenance["sources"]}
    assert roles == {"primary_document", "xbrl_package", "filing_summary"}
    for source in provenance["sources"]:
        assert len(source["sha256"]) == 64
        assert source["size_bytes"] > 0
        assert source["storage_key"].startswith("filings/")


@pytest.mark.parametrize("accession", ALL_FILINGS)
def test_the_fixture_carries_no_complete_source_document(accession: str) -> None:
    """Derived geometry only. A committed copy of a 1.5 MB filing would sit in history forever
    for content SEC hosts authoritatively."""
    fixture = load(accession)
    assert "raw_html" not in fixture
    for table in fixture["tables"]:
        assert set(table) == {"external_id", "source_offset", "raw_length"}
