"""The presentation linkbase: which concepts belong to which role URI.

This is the link that makes table ownership deterministic rather than positional.

    role URI                 already used for stage-3 attachment
      -> presentationLink    in the filing's own _pre.xml
      -> TextBlock concept   the concept the filer tagged the note's narrative with
      -> ix:nonNumeric span  the element in the primary document that WRAPS that narrative
      -> tables inside it    owned by that role's canonical footnote

Every step is published by the filer. Nothing is inferred from proximity, document offsets, or
title similarity, and no step needs a byte-offset map that `FilingSummary.xml` does not contain.

WHY NOT PARSE THE RENDERER'S PER-REPORT FILES. `FilingSummary.xml` names an `R9.htm` per report,
which would give ownership directly — but those files are generated by SEC's renderer and are not
in the `-xbrl.zip`. Acquiring them is 70 more HTTP requests per filing for information the filing
already contains. The linkbase is in the bytes already preserved.
"""

from __future__ import annotations

import xml.etree.ElementTree as ElementTree
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

from .errors import ExtractionError

XLINK = "{http://www.w3.org/1999/xlink}"
LINKBASE = "{http://www.xbrl.org/2003/linkbase}"

# A concept whose name ends in TextBlock carries a block of narrative. It is what the filer wraps
# around a note, and therefore what bounds the note in the document.
TEXT_BLOCK_SUFFIX = "TextBlock"


class PresentationLinkbaseError(ExtractionError):
    """The presentation linkbase could not be read."""


@dataclass(frozen=True)
class RolePresentation:
    """One presentation role and the concepts filed under it."""

    role_uri: str
    concepts: tuple[str, ...]

    @property
    def text_block_concepts(self) -> tuple[str, ...]:
        return tuple(c for c in self.concepts if c.endswith(TEXT_BLOCK_SUFFIX))


@dataclass
class PresentationLinkbase:
    """Every presentation role in a filing, and the concept-to-role index derived from it."""

    roles: dict[str, RolePresentation] = field(default_factory=dict)

    def concept_to_roles(self) -> dict[str, list[str]]:
        """Which roles each concept appears under.

        A concept can appear under several roles — a TextBlock under both the note role and a
        `...Tables` child role — so the value is a list. Callers resolve the ambiguity through the
        attachment they already audited rather than by picking one here.
        """
        index: dict[str, list[str]] = {}
        for role in self.roles.values():
            for concept in role.concepts:
                index.setdefault(concept, []).append(role.role_uri)
        return index

    def text_block_owners(self) -> dict[str, list[str]]:
        """Which roles each TextBlock concept appears under."""
        return {
            concept: roles
            for concept, roles in self.concept_to_roles().items()
            if concept.endswith(TEXT_BLOCK_SUFFIX)
        }


def _normalize_concept(href: str) -> str:
    """`aapl-20250927.xsd#us-gaap_DebtDisclosureTextBlock` to `us-gaap:DebtDisclosureTextBlock`.

    The linkbase writes the underscore form; the inline-XBRL document writes the colon form. They
    are the same concept, and comparing them unnormalized matches nothing.
    """
    fragment = href.split("#")[-1]
    return fragment.replace("_", ":", 1)


def parse_presentation(raw: bytes) -> PresentationLinkbase:
    """Parse a `_pre.xml` presentation linkbase."""
    try:
        root = ElementTree.fromstring(raw)
    except ElementTree.ParseError as error:
        raise PresentationLinkbaseError(
            f"presentation linkbase is not parseable: {error}"
        ) from error

    linkbase = PresentationLinkbase()
    for link in root.findall(f"{LINKBASE}presentationLink"):
        role_uri = link.get(f"{XLINK}role")
        if not role_uri:
            continue
        concepts = []
        for locator in link.findall(f"{LINKBASE}loc"):
            href = locator.get(f"{XLINK}href")
            if href:
                concepts.append(_normalize_concept(href))
        linkbase.roles[role_uri] = RolePresentation(role_uri=role_uri, concepts=tuple(concepts))

    if not linkbase.roles:
        raise PresentationLinkbaseError(
            "the presentation linkbase declares no roles. An empty linkbase is refused rather "
            "than returned: it would silently make every table unownable."
        )
    return linkbase


def read_presentation_from_package(path: Path) -> PresentationLinkbase:
    """Read the presentation linkbase out of a filing's `-xbrl.zip`.

    The member is named `<document>_pre.xml`; it is located by suffix rather than by constructing
    the name, because the document stem varies per filing and per agent.
    """
    try:
        with zipfile.ZipFile(path) as archive:
            members = [n for n in archive.namelist() if n.endswith("_pre.xml")]
            if not members:
                raise PresentationLinkbaseError(f"{path.name} contains no _pre.xml member")
            return parse_presentation(archive.read(members[0]))
    except zipfile.BadZipFile as error:
        raise PresentationLinkbaseError(f"{path.name} is not a readable archive") from error
